import express from 'express';
import crypto from 'crypto';
import prisma from '../database/index.js';
import { config } from '../config/index.js';
import { authenticateToken } from '../middleware/auth.js';
import { createAlert } from '../services/alertService.js';

const router = express.Router();

// Helper: Machine-to-machine authentication middleware for FusionAI webhook
function authenticateWorkflowSecret(req, res, next) {
  const secretHeader = req.headers['x-fusionai-secret'];
  const authHeader = req.headers['authorization'];
  let bearerToken = null;
  if (authHeader && authHeader.startsWith('Bearer ')) {
    bearerToken = authHeader.split(' ')[1];
  }

  const token = secretHeader || bearerToken;
  if (!token || token !== config.fusionAiSecret) {
    return res.status(401).json({
      success: false,
      error: 'Accès non autorisé. Secret de workflow invalide ou manquant.'
    });
  }
  next();
}

/**
 * Normalize water quantities: auto-convert any *Ml fields → *L (÷ 1000).
 * Supports both waterBudget object and zoneDecisions array.
 * The DB always stores liters; this is a defensive conversion for legacy payloads.
 */
function normalizeMlToLiters(obj) {
  if (!obj || typeof obj !== 'object') return obj;
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.endsWith('Ml') && typeof v === 'number') {
      out[k.slice(0, -2) + 'L'] = parseFloat((v / 1000).toFixed(3));
    } else {
      out[k] = v;
    }
  }
  return out;
}

/**
 * POST /api/ai-analysis
 * Machine-to-machine endpoint to record a new AI analysis generated by FusionAI workflow.
 * Features idempotency and auto-creation of unified AI alerts for high risk / warnings.
 */
router.post('/', authenticateWorkflowSecret, async (req, res) => {
  try {
    const payload = req.body;

    if (!payload || typeof payload !== 'object') {
      return res.status(400).json({ success: false, error: 'Payload JSON invalide.' });
    }

    const {
      timestamp,
      decisionStatus,
      validForMinutes,
      confidencePct,
      nextEvaluationMinutes,
      waterBudget,
      weatherAssessment,
      zoneDecisions,
      decisionSummary,
      warnings,
      sensorReadingId
    } = payload;

    // 1. Payload validation
    if (!timestamp || !decisionStatus || confidencePct === undefined || !decisionSummary) {
      return res.status(400).json({
        success: false,
        error: 'Champs requis manquants (timestamp, decisionStatus, confidencePct, decisionSummary).'
      });
    }

    const validStatuses = [
      'PROPOSED', 'IRRIGATE', 'DEFER', 'NO_IRRIGATION',
      'APPROVED', 'EXECUTING', 'COMPLETED', 'REJECTED'
    ];
    if (!validStatuses.includes(decisionStatus)) {
      return res.status(400).json({
        success: false,
        error: `decisionStatus invalide: ${decisionStatus}. Valeurs acceptées: ${validStatuses.join(', ')}`
      });
    }

    // 2. Idempotency check (by Idempotency-Key header or exact timestamp)
    const idempotencyKey = req.headers['idempotency-key'];
    let existing = null;
    if (idempotencyKey) {
      existing = await prisma.aIAnalysis.findUnique({
        where: { id: idempotencyKey }
      });
    } else {
      const parsedTimestamp = new Date(timestamp);
      if (!isNaN(parsedTimestamp.getTime())) {
        existing = await prisma.aIAnalysis.findFirst({
          where: { timestamp: parsedTimestamp }
        });
      }
    }

    if (existing) {
      return res.status(200).json({
        success: true,
        analysisId: existing.id,
        deduplicated: true,
        message: 'Analyse déjà enregistrée (déduplication appliquée).'
      });
    }

    // 3. Generate server-side unique ID
    const randomHash = crypto.randomBytes(3).toString('hex');
    const dateFormatted = new Date().toISOString().replace(/[-:T.]/g, '').slice(0, 14);
    const newId = idempotencyKey || `ai-analysis-${dateFormatted}-${randomHash}`;

    // 4. Normalize: ensure all water volume fields are stored in liters (not ml)
    const normalizedWaterBudget = normalizeMlToLiters(waterBudget || {});
    const normalizedZoneDecisions = Array.isArray(zoneDecisions)
      ? zoneDecisions.map(normalizeMlToLiters)
      : [];

    // 5. Resolve sensorReadingId: use provided or auto-link to latest sensor reading
    let resolvedSensorReadingId = null;
    if (sensorReadingId) {
      resolvedSensorReadingId = BigInt(sensorReadingId);
    } else {
      const fiveMinutesAgo = new Date(Date.now() - 5 * 60 * 1000);
      const latestReading = await prisma.sensorReading.findFirst({
        where: { timestamp: { gte: fiveMinutesAgo } },
        orderBy: { timestamp: 'desc' }
      });
      if (latestReading) {
        resolvedSensorReadingId = latestReading.id;
      }
    }

    // 6. Persistence with optional sensorReading relation
    const createdAnalysis = await prisma.aIAnalysis.create({
      data: {
        id: newId,
        timestamp: new Date(timestamp),
        decisionStatus,
        validForMinutes: validForMinutes || 60,
        confidencePct: parseFloat(confidencePct),
        nextEvaluationMinutes: nextEvaluationMinutes || 120,
        waterBudget: normalizedWaterBudget,
        weatherAssessment: weatherAssessment || {},
        zoneDecisions: normalizedZoneDecisions,
        decisionSummary,
        warnings: Array.isArray(warnings) ? warnings : [],
        sensorReadingId: resolvedSensorReadingId
      }
    });

    // 7. Auto-create Centralized Alerts from AI Warnings & Decisions
    try {
      // 7a. General AI Warnings
      if (Array.isArray(warnings)) {
        for (const w of warnings) {
          const wText = typeof w === 'string' ? w : w.message || JSON.stringify(w);
          const isCritical = /critique|urgence|danger|canicule|sécheresse|déficit|panne/i.test(wText);
          await createAlert({
            source: 'AI',
            category: 'AI',
            type: 'AI_WARNING',
            severity: isCritical ? 'high' : 'medium',
            message: `[IA] ${wText}`,
            metadata: { analysisId: newId }
          });
        }
      }

      // 7b. Critical Zone Moisture Deficits / Water Stress
      for (const zd of normalizedZoneDecisions) {
        if (zd.action === 'IRRIGATE' && (zd.riskLevel === 'HIGH' || zd.riskLevel === 'CRITICAL' || zd.soilMoistureStatus === 'CRITICAL_LOW')) {
          const zNum = zd.zoneId ? parseInt(String(zd.zoneId).replace(/\D/g, ''), 10) || null : null;
          await createAlert({
            source: 'AI',
            category: 'WATER',
            type: 'AI_WATER_STRESS',
            severity: zd.riskLevel === 'CRITICAL' ? 'critical' : 'high',
            zoneId: zNum,
            message: `[Stress Hydrique IA] Zone ${zd.zoneId || ''} (${zd.cropType || zd.crop || 'Culture'}) : ${zd.rationale || 'Apport en eau urgent requis'}`,
            metadata: { analysisId: newId, zoneDecision: zd }
          });
        }
      }

      // 7c. Deferral Notice
      if (decisionStatus === 'DEFER') {
        await createAlert({
          source: 'AI',
          category: 'AI',
          type: 'AI_IRRIGATION_DEFERRED',
          severity: 'info',
          message: `[Recommandation IA] Irrigation différée : ${decisionSummary}`,
          metadata: { analysisId: newId }
        });
      }
    } catch (alertErr) {
      console.warn('[AI Analysis] Warning creating linked alerts:', alertErr.message);
    }

    return res.status(201).json({
      success: true,
      analysisId: newId,
      linkedSensorReadingId: resolvedSensorReadingId ? resolvedSensorReadingId.toString() : null
    });
  } catch (err) {
    console.error('[AI Analysis Endpoint Error]', err);
    return res.status(500).json({ success: false, error: "Erreur interne du serveur lors de l'enregistrement." });
  }
});

/**
 * GET /api/ai-analysis
 * Lightweight summary list, ordered newest first, with pagination.
 */
router.get('/', authenticateToken, async (req, res) => {
  try {
    const page = Math.max(1, parseInt(req.query.page, 10) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));
    const skip = (page - 1) * limit;

    const total = await prisma.aIAnalysis.count();
    const totalPages = Math.ceil(total / limit) || 1;

    const rows = await prisma.aIAnalysis.findMany({
      orderBy: { timestamp: 'desc' },
      skip,
      take: limit,
      select: {
        id: true,
        timestamp: true,
        decisionStatus: true,
        validForMinutes: true,
        confidencePct: true,
        nextEvaluationMinutes: true,
        decisionSummary: true,
        zoneDecisions: true,
        warnings: true,
        createdAt: true,
        sensorReadingId: true,
        _count: {
          select: { irrigationCycles: true }
        }
      }
    });

    const summaries = rows.map((row) => {
      const zones = Array.isArray(row.zoneDecisions) ? row.zoneDecisions : [];
      const warns = Array.isArray(row.warnings) ? row.warnings : [];

      return {
        id: row.id,
        timestamp: row.timestamp.toISOString(),
        decisionStatus: row.decisionStatus,
        validForMinutes: row.validForMinutes,
        confidencePct: row.confidencePct,
        nextEvaluationMinutes: row.nextEvaluationMinutes,
        decisionSummary: row.decisionSummary,
        zoneCount: zones.length,
        warningCount: warns.length,
        linkedSensorReadingId: row.sensorReadingId ? row.sensorReadingId.toString() : null,
        irrigationCyclesCount: row._count.irrigationCycles,
        createdAt: row.createdAt.toISOString()
      };
    });

    return res.json({
      success: true,
      analyses: summaries,
      pagination: {
        total,
        page,
        limit,
        totalPages
      }
    });
  } catch (err) {
    console.error('[AI Analysis List Error]', err);
    return res.status(500).json({ success: false, error: 'Impossible de récupérer la liste des analyses.' });
  }
});

/**
 * GET /api/ai-analysis/latest
 * Return the most recent AI analysis for real-time dashboard widgets
 */
router.get('/latest', authenticateToken, async (req, res) => {
  try {
    const latest = await prisma.aIAnalysis.findFirst({
      orderBy: { timestamp: 'desc' },
      include: {
        sensorReading: {
          select: {
            id: true,
            timestamp: true,
            zone1Soil: true,
            zone2Soil: true,
            zone3Soil: true,
            waterLevel: true,
            volumeLiters: true,
            temperature: true,
            airHumidity: true
          }
        }
      }
    });

    if (!latest) {
      return res.json({ success: true, analysis: null });
    }

    return res.json({
      success: true,
      analysis: {
        id: latest.id,
        timestamp: latest.timestamp.toISOString(),
        decisionStatus: latest.decisionStatus,
        validForMinutes: latest.validForMinutes,
        confidencePct: latest.confidencePct,
        nextEvaluationMinutes: latest.nextEvaluationMinutes,
        waterBudget: latest.waterBudget || {},
        weatherAssessment: latest.weatherAssessment || {},
        zoneDecisions: Array.isArray(latest.zoneDecisions) ? latest.zoneDecisions : [],
        decisionSummary: latest.decisionSummary,
        warnings: Array.isArray(latest.warnings) ? latest.warnings : [],
        createdAt: latest.createdAt.toISOString(),
        sensorReading: latest.sensorReading
          ? {
              ...latest.sensorReading,
              id: latest.sensorReading.id.toString(),
              timestamp: latest.sensorReading.timestamp.toISOString()
            }
          : null
      }
    });
  } catch (err) {
    console.error('[AI Analysis Latest Error]', err);
    return res.status(500).json({ success: false, error: 'Impossible de récupérer la dernière analyse.' });
  }
});

/**
 * GET /api/ai-analysis/:id
 * Full analysis details with linked sensor reading and irrigation cycles.
 */
router.get('/:id', authenticateToken, async (req, res) => {
  try {
    const { id } = req.params;
    const row = await prisma.aIAnalysis.findUnique({
      where: { id },
      include: {
        sensorReading: {
          select: {
            id: true,
            timestamp: true,
            zone1Soil: true,
            zone2Soil: true,
            zone3Soil: true,
            waterLevel: true,
            volumeLiters: true,
            temperature: true,
            airHumidity: true
          }
        },
        irrigationCycles: {
          select: {
            id: true,
            zoneId: true,
            plant: true,
            requestedLiters: true,
            deliveredLiters: true,
            status: true,
            startTime: true,
            endTime: true
          }
        }
      }
    });

    if (!row) {
      return res.status(404).json({
        success: false,
        error: "Cette analyse n'est plus disponible."
      });
    }

    const fullAnalysis = {
      id: row.id,
      timestamp: row.timestamp.toISOString(),
      decisionStatus: row.decisionStatus,
      validForMinutes: row.validForMinutes,
      confidencePct: row.confidencePct,
      nextEvaluationMinutes: row.nextEvaluationMinutes,
      waterBudget: row.waterBudget || {},
      weatherAssessment: row.weatherAssessment || {},
      zoneDecisions: Array.isArray(row.zoneDecisions) ? row.zoneDecisions : [],
      decisionSummary: row.decisionSummary,
      warnings: Array.isArray(row.warnings) ? row.warnings : [],
      createdAt: row.createdAt.toISOString(),
      sensorReading: row.sensorReading
        ? {
            ...row.sensorReading,
            id: row.sensorReading.id.toString(),
            timestamp: row.sensorReading.timestamp.toISOString()
          }
        : null,
      irrigationCycles: row.irrigationCycles.map((c) => ({
        ...c,
        startTime: c.startTime.toISOString(),
        endTime: c.endTime ? c.endTime.toISOString() : null
      }))
    };

    return res.json({
      success: true,
      analysis: fullAnalysis
    });
  } catch (err) {
    console.error('[AI Analysis Detail Error]', err);
    return res.status(500).json({ success: false, error: "Impossible de récupérer le détail de l'analyse." });
  }
});

export default router;
