import express from 'express';
import crypto from 'crypto';
import prisma from '../database/index.js';
import { config } from '../config/index.js';
import { authenticateToken } from '../middleware/auth.js';

const router = express.Router();

// Helper: Machine-to-machine authentication middleware for FusionAI / n8n webhook
function authenticateWorkflowSecret(req, res, next) {
  const secretHeader = req.headers['x-fusionai-secret'] || req.headers['x-n8n-secret'];
  const authHeader = req.headers['authorization'];
  let bearerToken = null;
  if (authHeader && authHeader.startsWith('Bearer ')) {
    bearerToken = authHeader.split(' ')[1];
  }

  const token = secretHeader || bearerToken;
  if (!token || token !== config.fusionAiSecret) {
    return res.status(401).json({
      success: false,
      error: 'Accès non autorisé. Secret de workflow invalide ou manquant.'
    });
  }
  next();
}

/**
 * Normalize water quantities: auto-convert any *Ml fields → *L (÷ 1000).
 * Supports both waterBudget object and zoneDecisions array.
 * The DB always stores liters; this is a defensive conversion for legacy payloads.
 */
function normalizeMlToLiters(obj) {
  if (!obj || typeof obj !== 'object') return obj;
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.endsWith('Ml') && typeof v === 'number') {
      // Rename availableMl → availableL, wateringMl → wateringL, etc.
      out[k.slice(0, -2) + 'L'] = parseFloat((v / 1000).toFixed(3));
    } else {
      out[k] = v;
    }
  }
  return out;
}

/**
 * POST /api/ai-analysis
 * Machine-to-machine endpoint to record a new AI analysis generated by FusionAI workflow.
 * Features idempotency (deduplication on timestamp / Idempotency-Key header) and server-side ID assignment.
 */
router.post('/', authenticateWorkflowSecret, async (req, res) => {
  try {
    const payload = req.body;

    if (!payload || typeof payload !== 'object') {
      return res.status(400).json({ success: false, error: 'Payload JSON invalide.' });
    }

    const {
      timestamp,
      decisionStatus,
      validForMinutes,
      confidencePct,
      nextEvaluationMinutes,
      waterBudget,
      weatherAssessment,
      zoneDecisions,
      decisionSummary,
      warnings
    } = payload;

    // 1. Payload validation
    if (!timestamp || !decisionStatus || confidencePct === undefined || !decisionSummary) {
      return res.status(400).json({
        success: false,
        error: 'Champs requis manquants (timestamp, decisionStatus, confidencePct, decisionSummary).'
      });
    }

    const validStatuses = [
      'PROPOSED', 'IRRIGATE', 'DEFER', 'NO_IRRIGATION',
      'APPROVED', 'EXECUTING', 'COMPLETED', 'REJECTED'
    ];
    if (!validStatuses.includes(decisionStatus)) {
      return res.status(400).json({
        success: false,
        error: `decisionStatus invalide: ${decisionStatus}. Valeurs acceptées: ${validStatuses.join(', ')}`
      });
    }

    // 2. Idempotency check (by Idempotency-Key header or exact timestamp)
    const idempotencyKey = req.headers['idempotency-key'];
    let existing = null;
    if (idempotencyKey) {
      existing = await prisma.aIAnalysis.findUnique({
        where: { id: idempotencyKey }
      });
    } else {
      const parsedTimestamp = new Date(timestamp);
      if (!isNaN(parsedTimestamp.getTime())) {
        existing = await prisma.aIAnalysis.findFirst({
          where: { timestamp: parsedTimestamp }
        });
      }
    }

    if (existing) {
      return res.status(200).json({
        success: true,
        analysisId: existing.id,
        deduplicated: true,
        message: 'Analyse déjà enregistrée (déduplication appliquée).'
      });
    }

    // 3. Generate server-side unique ID
    const randomHash = crypto.randomBytes(3).toString('hex');
    const dateFormatted = new Date().toISOString().replace(/[-:T.]/g, '').slice(0, 14);
    const newId = idempotencyKey || `ai-analysis-${dateFormatted}-${randomHash}`;

    // 4. Normalize: ensure all water volume fields are stored in liters (not ml)
    const normalizedWaterBudget = normalizeMlToLiters(waterBudget || {});
    const normalizedZoneDecisions = Array.isArray(zoneDecisions)
      ? zoneDecisions.map(normalizeMlToLiters)
      : [];

    // 5. Persistence
    await prisma.aIAnalysis.create({
      data: {
        id: newId,
        timestamp: new Date(timestamp),
        decisionStatus,
        validForMinutes: validForMinutes || 60,
        confidencePct: parseFloat(confidencePct),
        nextEvaluationMinutes: nextEvaluationMinutes || 120,
        waterBudget: normalizedWaterBudget,
        weatherAssessment: weatherAssessment || {},
        zoneDecisions: normalizedZoneDecisions,
        decisionSummary,
        warnings: Array.isArray(warnings) ? warnings : []
      }
    });

    return res.status(201).json({
      success: true,
      analysisId: newId
    });
  } catch (err) {
    console.error('[AI Analysis Endpoint Error]', err);
    return res.status(500).json({ success: false, error: "Erreur interne du serveur lors de l'enregistrement." });
  }
});

/**
 * GET /api/ai-analysis
 * Lightweight summary list, ordered newest first, with pagination.
 */
router.get('/', authenticateToken, async (req, res) => {
  try {
    const page = Math.max(1, parseInt(req.query.page, 10) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));
    const skip = (page - 1) * limit;

    const total = await prisma.aIAnalysis.count();
    const totalPages = Math.ceil(total / limit) || 1;

    const rows = await prisma.aIAnalysis.findMany({
      orderBy: { timestamp: 'desc' },
      skip,
      take: limit,
      select: {
        id: true,
        timestamp: true,
        decisionStatus: true,
        validForMinutes: true,
        confidencePct: true,
        nextEvaluationMinutes: true,
        decisionSummary: true,
        zoneDecisions: true,
        warnings: true,
        createdAt: true
      }
    });

    // Map summary items without heavy nested bodies
    const summaries = rows.map((row) => {
      const zones = Array.isArray(row.zoneDecisions) ? row.zoneDecisions : [];
      const warns = Array.isArray(row.warnings) ? row.warnings : [];

      return {
        id: row.id,
        timestamp: row.timestamp.toISOString(),
        decisionStatus: row.decisionStatus,
        validForMinutes: row.validForMinutes,
        confidencePct: row.confidencePct,
        nextEvaluationMinutes: row.nextEvaluationMinutes,
        decisionSummary: row.decisionSummary,
        zoneCount: zones.length,
        warningCount: warns.length,
        createdAt: row.createdAt.toISOString()
      };
    });

    return res.json({
      success: true,
      analyses: summaries,
      pagination: {
        total,
        page,
        limit,
        totalPages
      }
    });
  } catch (err) {
    console.error('[AI Analysis List Error]', err);
    return res.status(500).json({ success: false, error: 'Impossible de récupérer la liste des analyses.' });
  }
});

/**
 * GET /api/ai-analysis/:id
 * Full analysis details for a given ID.
 */
router.get('/:id', authenticateToken, async (req, res) => {
  try {
    const { id } = req.params;
    const row = await prisma.aIAnalysis.findUnique({
      where: { id }
    });

    if (!row) {
      return res.status(404).json({
        success: false,
        error: "Cette analyse n'est plus disponible."
      });
    }

    const fullAnalysis = {
      id: row.id,
      timestamp: row.timestamp.toISOString(),
      decisionStatus: row.decisionStatus,
      validForMinutes: row.validForMinutes,
      confidencePct: row.confidencePct,
      nextEvaluationMinutes: row.nextEvaluationMinutes,
      waterBudget: row.waterBudget || {},
      weatherAssessment: row.weatherAssessment || {},
      zoneDecisions: Array.isArray(row.zoneDecisions) ? row.zoneDecisions : [],
      decisionSummary: row.decisionSummary,
      warnings: Array.isArray(row.warnings) ? row.warnings : [],
      createdAt: row.createdAt.toISOString()
    };

    return res.json({
      success: true,
      analysis: fullAnalysis
    });
  } catch (err) {
    console.error('[AI Analysis Detail Error]', err);
    return res.status(500).json({ success: false, error: "Impossible de récupérer le détail de l'analyse." });
  }
});

export default router;
